# Generated by Django 5.0.6 on 2024-06-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_litros', models.FloatField()),
                ('valor_abastecido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imposto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bomba')),
            ],
        ),
        migrations.AddField(
            model_name='bomba',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tanque'),
        ),
    ]
