# Generated by Django 5.0.6 on 2024-06-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tanque_tipo_bomba_numero_tanque_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanque',
            old_name='nome',
            new_name='nome_tanque',
        ),
    ]
