# Generated by Django 5.0.6 on 2024-06-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_tanque_nome_tanque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomba',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='tanque',
            name='nome_tanque',
        ),
        migrations.AddField(
            model_name='bomba',
            name='bomba_utilizada',
            field=models.CharField(choices=[('GASOLINA 1', 'Gasolina bomba 1'), ('GASOLINA 2', 'Gasolina bomba 2'), ('DIESEL 1', 'Diesel bomba 1'), ('DIESEL 2', 'Diesel bomba 2')], default=3, max_length=50),
            preserve_default=False,
        ),
    ]
